module.exports = [
    {
        id: "ge-br",
        name: "ge",
        country: "BR",
        language: "pt-BR",
        ingestion_type: "rss",
        url: "https://ge.globo.com/",
        feed_url: "https://ge.globo.com/rss/ge/futebol/",
        championship_ids: ["brasileirao2026", "libertadores2026", "bundesliga2526", "ligue12526", "mls2026", "saudipro2526", "ucl2526", "laliga2526", "premier2526", "wc2026"],
        priority: 100,
        enabled: true,
        notes: "Fonte principal para futebol em português.",
    },
    {
        id: "espn-br",
        name: "ESPN Brasil",
        country: "BR",
        language: "pt-BR",
        ingestion_type: "scrape",
        url: "https://www.espn.com.br/futebol/",
        championship_ids: ["brasileirao2026", "libertadores2026", "bundesliga2526", "ligue12526", "mls2026", "saudipro2526", "ucl2526", "laliga2526", "premier2526", "wc2026"],
        priority: 95,
        enabled: true,
    },
    {
        id: "uol-futebol",
        name: "UOL Esporte",
        country: "BR",
        language: "pt-BR",
        ingestion_type: "scrape",
        url: "https://www.uol.com.br/esporte/futebol/",
        championship_ids: ["brasileirao2026", "libertadores2026", "mls2026", "saudipro2526", "wc2026"],
        priority: 90,
        enabled: true,
    },
    {
        id: "gazeta-esportiva",
        name: "Gazeta Esportiva",
        country: "BR",
        language: "pt-BR",
        ingestion_type: "scrape",
        url: "https://www.gazetaesportiva.com/futebol/",
        championship_ids: ["brasileirao2026", "libertadores2026", "bundesliga2526", "ligue12526", "ucl2526", "laliga2526", "premier2526"],
        priority: 88,
        enabled: true,
    },
    {
        id: "lance",
        name: "LANCE!",
        country: "BR",
        language: "pt-BR",
        ingestion_type: "scrape",
        url: "https://www.lance.com.br/",
        championship_ids: ["brasileirao2026", "libertadores2026", "bundesliga2526", "ligue12526", "mls2026", "saudipro2526", "ucl2526", "laliga2526", "premier2526"],
        priority: 86,
        enabled: true,
    },
    {
        id: "marca",
        name: "Marca",
        country: "ES",
        language: "es",
        ingestion_type: "rss",
        url: "https://www.marca.com/",
        feed_url: "https://e00-marca.uecdn.es/rss/futbol.xml",
        championship_ids: ["laliga2526", "bundesliga2526", "ligue12526", "libertadores2026", "saudipro2526", "ucl2526", "wc2026"],
        priority: 100,
        enabled: true,
    },
    {
        id: "as",
        name: "AS",
        country: "ES",
        language: "es",
        ingestion_type: "rss",
        url: "https://as.com/futbol/",
        feed_url: "https://futbol.as.com/rss/",
        championship_ids: ["laliga2526", "bundesliga2526", "ligue12526", "libertadores2026", "saudipro2526", "ucl2526", "wc2026"],
        priority: 96,
        enabled: true,
    },
    {
        id: "mundo-deportivo",
        name: "Mundo Deportivo",
        country: "ES",
        language: "es",
        ingestion_type: "scrape",
        url: "https://www.mundodeportivo.com/futbol",
        championship_ids: ["laliga2526", "bundesliga2526", "ligue12526", "libertadores2026", "saudipro2526", "ucl2526", "wc2026"],
        priority: 92,
        enabled: true,
    },
    {
        id: "sport-es",
        name: "SPORT",
        country: "ES",
        language: "es",
        ingestion_type: "scrape",
        url: "https://www.sport.es/es/futbol/",
        championship_ids: ["bundesliga2526", "ligue12526", "laliga2526", "ucl2526"],
        priority: 90,
        enabled: true,
    },
    {
        id: "eldesmarque",
        name: "ElDesmarque",
        country: "ES",
        language: "es",
        ingestion_type: "scrape",
        url: "https://www.eldesmarque.com/futbol",
        championship_ids: ["bundesliga2526", "ligue12526", "laliga2526", "ucl2526"],
        priority: 86,
        enabled: true,
    },
    {
        id: "guardian-football",
        name: "The Guardian Football",
        country: "GB",
        language: "en",
        ingestion_type: "rss",
        url: "https://www.theguardian.com/football",
        feed_url: "https://feeds.theguardian.com/theguardian/football/rss",
        championship_ids: ["bundesliga2526", "ligue12526", "mls2026", "saudipro2526", "premier2526", "ucl2526", "wc2026"],
        priority: 100,
        enabled: true,
    },
    {
        id: "bbc-football",
        name: "BBC Sport Football",
        country: "GB",
        language: "en",
        ingestion_type: "scrape",
        url: "https://www.bbc.com/sport/football",
        championship_ids: ["bundesliga2526", "ligue12526", "mls2026", "saudipro2526", "premier2526", "ucl2526", "wc2026"],
        priority: 96,
        enabled: true,
    },
    {
        id: "sky-sports-football",
        name: "Sky Sports Football",
        country: "GB",
        language: "en",
        ingestion_type: "scrape",
        url: "https://www.skysports.com/football",
        championship_ids: ["bundesliga2526", "ligue12526", "premier2526", "ucl2526", "saudipro2526"],
        priority: 92,
        enabled: true,
    },
    {
        id: "telegraph-football",
        name: "The Telegraph Football",
        country: "GB",
        language: "en",
        ingestion_type: "scrape",
        url: "https://www.telegraph.co.uk/football/",
        championship_ids: ["bundesliga2526", "ligue12526", "premier2526", "ucl2526", "saudipro2526"],
        priority: 88,
        enabled: true,
    },
    {
        id: "independent-football",
        name: "The Independent Football",
        country: "GB",
        language: "en",
        ingestion_type: "scrape",
        url: "https://www.independent.co.uk/sport/football",
        championship_ids: ["bundesliga2526", "ligue12526", "premier2526", "ucl2526", "saudipro2526"],
        priority: 84,
        enabled: true,
    },
    {
        id: "uefa",
        name: "UEFA",
        country: "EU",
        language: "en",
        ingestion_type: "scrape",
        url: "https://www.uefa.com/uefachampionsleague/news/",
        championship_ids: ["ucl2526", "wc2026", "bundesliga2526", "ligue12526"],
        priority: 100,
        enabled: true,
        notes: "Fonte oficial do torneio para Champions.",
    },
];
