const MARKET_TEMPLATES = {
  match_winner: {
    scope: "match",
    prediction_type: "single_choice",
    title: "Vencedor da partida",
    description: "Escolha quem vence ou se o jogo termina empatado.",
    help_text: "Acerte o vencedor ou empate para pontuar nessa partida.",
    points_exact: 3,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: true,
    supports_confidence: true,
    is_required: true,
  },
  exact_score: {
    scope: "match",
    prediction_type: "score",
    title: "Placar exato",
    description: "Acerte os gols dos dois lados para ganhar a pontuação maxima.",
    help_text: "Crave o placar completo para levar a pontuacao cheia.",
    points_exact: 10,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: true,
    supports_confidence: false,
    is_required: true,
  },
  home_goals: {
    scope: "match",
    prediction_type: "number",
    title: "Gols do time mandante",
    description: "Aposte quantos gols o mandante vai marcar.",
    help_text: "Voce pontua ao acertar os gols do time da casa.",
    points_exact: 4,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: true,
    supports_confidence: false,
    is_required: false,
  },
  away_goals: {
    scope: "match",
    prediction_type: "number",
    title: "Gols do visitante",
    description: "Aposte quantos gols o visitante vai marcar.",
    help_text: "Voce pontua ao acertar os gols do time visitante.",
    points_exact: 4,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: true,
    supports_confidence: false,
    is_required: false,
  },
  total_goals: {
    scope: "match",
    prediction_type: "number",
    title: "Total de gols",
    description: "Some os gols da partida e aposte no total.",
    help_text: "Boa opcao para quem quer ler o ritmo da partida sem travar no placar.",
    points_exact: 4,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: true,
    supports_confidence: false,
    is_required: false,
  },
  both_score: {
    scope: "match",
    prediction_type: "single_choice",
    title: "Ambos marcam",
    description: "Escolha se os dois times vao marcar no jogo.",
    help_text: "Mercado simples de sim ou nao para jogos mais imprevisiveis.",
    points_exact: 2,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: true,
    is_required: false,
  },
  first_team_to_score: {
    scope: "match",
    prediction_type: "team",
    title: "Primeiro time a marcar",
    description: "Aposte quem abre o placar na partida.",
    help_text: "Ideal para jogos em que voce sente um time comecando mais forte.",
    points_exact: 3,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: true,
    is_required: false,
  },
  qualified_teams: {
    scope: "phase",
    prediction_type: "multi_choice",
    title: "Classificados da fase",
    description: "Escolha quem avanca em uma fase especifica.",
    help_text: "Mercado-chave para formatos de mata-mata e campeonato.",
    points_exact: 8,
    points_partial: 4,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
  semifinalists: {
    scope: "phase",
    prediction_type: "multi_choice",
    title: "Semifinalistas",
    description: "Escolha os quatro semifinalistas do torneio.",
    help_text: "Mercado muito bom para virada de ranking no mata-mata.",
    points_exact: 12,
    points_partial: 6,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
  finalists: {
    scope: "phase",
    prediction_type: "multi_choice",
    title: "Finalistas",
    description: "Escolha quem chega a grande final.",
    help_text: "Um dos mercados mais valiosos para ligas competitivas.",
    points_exact: 12,
    points_partial: 6,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
  champion: {
    scope: "tournament",
    prediction_type: "team",
    title: "Campeao",
    description: "Escolha quem levanta a taca.",
    help_text: "Mercado classico do bolao.",
    points_exact: 20,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: true,
  },
  top_scorer: {
    scope: "tournament",
    prediction_type: "single_choice",
    title: "Artilheiro",
    description: "Escolha quem termina o torneio como artilheiro.",
    help_text: "Mercado simples e popular.",
    points_exact: 15,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
  power_play: {
    scope: "special",
    prediction_type: "single_choice",
    title: "Power Play",
    description: "Escolha poucos mercados para dobrar a pontuacao em momentos-chave.",
    help_text: "Use com estrategia.",
    points_exact: 0,
    points_partial: 0,
    multiplier: 2,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
  confidence_pick: {
    scope: "special",
    prediction_type: "number",
    title: "Confidence",
    description: "Distribua pesos nas apostas de uma rodada conforme sua confianca.",
    help_text: "Quanto maior o peso, maior o impacto da aposta.",
    points_exact: 0,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: true,
    is_required: false,
  },
  survivor_pick: {
    scope: "special",
    prediction_type: "team",
    title: "Survivor",
    description: "Escolha uma selecao por rodada sem repetir.",
    help_text: "Errou, caiu. Acertou, segue vivo.",
    points_exact: 5,
    points_partial: 0,
    multiplier: 1,
    supports_power_play: false,
    supports_confidence: false,
    is_required: false,
  },
};

function toMarketDocId(bolaoId, templateId, orderIndex) {
  return `${bolaoId}_${templateId}_${orderIndex}`;
}

function toMatchMarketDocId(bolaoId, templateId, matchId) {
  return `${bolaoId}_${templateId}_${matchId}`;
}

function buildBolaoMarkets({ bolaoId, selectedMarketIds = [], matches = [] }) {
  const builtMarkets = [];
  let orderIndex = 0;

  for (const templateId of selectedMarketIds) {
    const template = MARKET_TEMPLATES[templateId];
    if (!template) continue;

    if (template.scope === "match" && matches.length) {
      for (const match of matches) {
        builtMarkets.push({
          id: toMatchMarketDocId(bolaoId, templateId, match.id),
          bolao_id: bolaoId,
          template_id: templateId,
          slug: templateId,
          scope: template.scope,
          title: `${template.title} · ${match.home_team_code || "CASA"} x ${match.away_team_code || "FORA"}`,
          description: template.description,
          help_text: template.help_text,
          match_id: match.id,
          phase_id: match.stage || null,
          group_id: match.group_id || null,
          is_required: template.is_required,
          opens_at: null,
          closes_at: match.match_date || null,
          status: "open",
          points_exact: template.points_exact,
          points_partial: template.points_partial,
          multiplier: template.multiplier,
          supports_power_play: template.supports_power_play,
          supports_confidence: template.supports_confidence,
          order_index: orderIndex++,
          prediction_type: template.prediction_type,
        });
      }
      continue;
    }

    builtMarkets.push({
      id: toMarketDocId(bolaoId, templateId, orderIndex),
      bolao_id: bolaoId,
      template_id: templateId,
      slug: templateId,
      scope: template.scope,
      title: template.title,
      description: template.description,
      help_text: template.help_text,
      match_id: null,
      phase_id: null,
      group_id: null,
      is_required: template.is_required,
      opens_at: null,
      closes_at: null,
      status: "open",
      points_exact: template.points_exact,
      points_partial: template.points_partial,
      multiplier: template.multiplier,
      supports_power_play: template.supports_power_play,
      supports_confidence: template.supports_confidence,
      order_index: orderIndex++,
      prediction_type: template.prediction_type,
    });
  }

  return builtMarkets;
}

module.exports = {
  buildBolaoMarkets,
};
